### PR TITLE
Mobile footer and ipad horizontal view

### PR DESCRIPTION
**Pull request by maenad**
Related to issues #41 ND #54 

----------- 

Hello!
Changes have been made as mentioned in the title. Please let me know if there is any issue on my PR so I can fix it.

One detail I noticed is that the media queries for phone is max-width: 400px and most phones nowadays are over 400px width, so might be good idea to bump it to 500px.

image
image

### CODE REVIEW

**Comment by DevrajDC** [comment]
Looks good to me. I am merging this now! :)

**Comment by maenad** [comment]
My PR still does not appear as accepted in the Hacktoberfest website, not sure if it is missing a tag here or if it has delay. Do I haee to put the tag myself anywhere?

Thanks in advance!

image

**Comment by DevrajDC** [comment]
I have already added the label. It might take some time to reflect maybe. :(

**Comment by maenad** [comment]
> I have already added the label. It might take some time to reflect maybe. :(

Not a problem, i will be paying attention to it during the day and if it doesn't change I'll let you know through Discord or here so we can troubleshoot

**Comment by DevrajDC** [comment]
> > I have already added the label. It might take some time to reflect maybe. :(
> 
> Not a problem, i will be paying attention to it during the day and if it doesn't change I'll let you know through Discord or here so we can troubleshoot

Yeah sure! Or else we'll make a new one :)

**Pull request merged**
