### PR TITLE
updated 

### PR DESCRIPTION
**Pull request by Barenyakumar**
updated the features section

### CODE REVIEW

**Comment by DevrajDC** [comment]
@Barenyakumar any update on this PR? @Prathamkrishna please check on this as soon as you get free.

**Comment by sakshamgurbhele** [comment]
@Prathamkrishna please look into the matter, we need to close this PR if it is done, the last commit was 2 months ago.

**Comment by Prathamkrishna** [comment]
@sakshamgurbhele @DevrajDC will look into this today.

**Comment by Prathamkrishna** [comment]
hey @Barenyakumar could you center align the text in the mobile mode?
Also, create a new PR for the same. 
I'll close this PR as soon as  you're done.

**Comment by DevrajDC** [comment]
Closing this PR since there's not much updates on this. Also new issues are creating so if anyone wants than take it up asap.

**Pull request closed without merging**
