### PR TITLE
Sayuri/enhancement/title update

### PR DESCRIPTION
**Pull request by SAYUK09**
name: pull request
description: Create a pull request
title: "minor enhancements"
labels: [enhancement, Hacktoberfest]
body:
  - type: Title Updated
    id: Changes the title of `accounts` page to `Linkify | Accounts`
    attributes:
      label: enhancement
  - type: CSS
    id: Added `transition` property to buttons for a smooth hover effect
    attributes:
      label:  N/A

  - type: textarea
    id: solution
    attributes:
      label: Does your code changes make any other feature broke? (If Yes, State reason)
    validations: No
      required: true
  
  - type: markdown
    attributes:
      value: |
        You can also join our [Discord community](https://discord.gg/druweDMn3s)
        Feel free to check out other cool repositories of the Design and Code Community [here](https://github.com/Design-and-Code)

### CODE REVIEW

**Comment by SAYUK09** [comment]
@DevrajDC Here's the toggle button and few small fixes.
Could you please look into it and let me know if I have to do anything more from my side

**Comment by nimishjn** [comment]
Hey @SAYUK09, could you fix the merge conflicts and also provide some more details on what changes you have made? 

A few changes that you made were assigned to another contributor, hence the merge conflicts.

**Comment by SAYUK09** [comment]
> Hey @SAYUK09, could you fix the merge conflicts and also provide some more details on what changes you have made?
> 
> A few changes that you made were assigned to another contributor, hence the merge conflicts.

@nimishjn Hey, Thanks for looking in. I've made a toggle button, update the title of the `account` page and fixed small bugs like, the `Features` Heading wasn't visible in dark mode.
But seems like other folk also have built a toggle button. Should we go with the merged changes?
Please let me know, thanks.

**Comment by nimishjn** [comment]
> > Hey @SAYUK09, could you fix the merge conflicts and also provide some more details on what changes you have made?
> > A few changes that you made were assigned to another contributor, hence the merge conflicts.
> 
> @nimishjn Hey, Thanks for looking in. I've made a toggle button, update the title of the `account` page and fixed small bugs like, the `Features` Heading wasn't visible in dark mode. But seems like other folk also have built a toggle button. Should we go with the merged changes? Please let me know, thanks.

@SAYUK09 Unfortunately, these changes are already implemented by the other contributor. We will go with the already merged changes because the maintainers have decided to go with a toggle instead of a switch. 

My suggestion for this would be:
- Fetch the latest changes
- Find an issue (Enhancement or bug)
- Create an issue under the `Issues` tab by providing adequate details
- Start working on it once we assign it to you

This will minimize the conflicts and the maintainers will be able to track your work. 
For more information about issues creation, head to [CONTRIBUTING.md](https://github.com/Design-and-Code/Linkify/blob/main/CONTRIBUTING.md). You can also ping me or any other maintainer on our discord server if you have any doubts.

**Comment by SAYUK09** [comment]
> > > Hey @SAYUK09, could you fix the merge conflicts and also provide some more details on what changes you have made?
> > > A few changes that you made were assigned to another contributor, hence the merge conflicts.
> > 
> > 
> > @nimishjn Hey, Thanks for looking in. I've made a toggle button, update the title of the `account` page and fixed small bugs like, the `Features` Heading wasn't visible in dark mode. But seems like other folk also have built a toggle button. Should we go with the merged changes? Please let me know, thanks.
> 
> @SAYUK09 Unfortunately, these changes are already implemented by the other contributor. We will go with the already merged changes because the maintainers have decided to go with a toggle instead of a switch.
> 
> My suggestion for this would be:
> 
> * Fetch the latest changes
> * Find an issue (Enhancement or bug)
> * Create an issue under the `Issues` tab by providing adequate details
> * Start working on it once we assign it to you
> 
> This will minimize the conflicts and the maintainers will be able to track your work. For more information about issues creation, head to [CONTRIBUTING.md](https://github.com/Design-and-Code/Linkify/blob/main/CONTRIBUTING.md). You can also ping me or any other maintainer on our discord server if you have any doubts.

Thanks for getting back. I understand. I should have created an issue earlier. My bad.
Have a great day.

**Comment by DevrajDC** [comment]
Heyy, it's fine. I am giving hacktoberfest-accepted label for your valuable contribution.

**Comment by DevrajDC** [comment]
Closing this PR now 🚀

**Pull request closed without merging**
